#pragma config(Sensor, in1,		 analog1,				 sensorAnalog)
#pragma config(Sensor, dgtl1,  limitSwitch, sensorTouch)
#pragma config(Sensor, dgtl2,  rangeSensor, sensorSONAR)
#pragma config(Sensor, dgtl10, digital10,			 sensorDigitalOut)
#pragma config(Sensor, dgtl11, digital11,			 sensorDigitalOut)
#pragma config(Sensor, dgtl12, digital12,			 sensorDigitalOut)
#pragma config(Motor,	 port1,						rightMotor,		 tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,	 port10,					leftMotor,		 tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor, port2, armMotor, tmotorVex393_HBridge, openLoop, reversed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

// Global Variables
int freq, ambient_level, slow_level, stop_level, expose_time, steer_sensitivity, forward_speed, slow_speed, spin_speed;

int arm_down_speed, arm_up_speed, arm_down_time, arm_up_time, arm_pause_time;

// initialize PD values for the global uses - will be modified at the appropriate timing in ReadPD function.
int PD0, PD1, PD2, PD3, PD4, PD5, PD6, PD7, PD_sum;
// initialize max values
int max_val, max_no = 0;

// Range sensor and exit parameters
int no_wall_threshold, scan_spin_speed;

/*The accumulator accumulates(or integrates) the rectified signal over a period of time (set by the expose and read)
The accumulated voltage read by SensorValue[analog1](an analog voltage) is read by the controller.
The expose_time period essentially set the ?gain? or ?sensitivity? of the overall circuit.*/
int Expose_and_read(){
	SensorValue[digital11] = 1; // close the shutter, clear the film, and increment the counter
	delay(5); // Wait for 5ms for things to settle
	SensorValue[digital11] = 0; // open shutter for exposure
	delay(expose_time); // expose time = 3ms to 8ms (can be adjusted)
	int intensity = SensorValue[analog1]; // get the IR intensity reading
	return intensity; // return the analog input 1
}

/*Read_PD calculates PD_sum which is the sum of all 8 photo diodes?outputs.
PD_sum is a measure of the distance between the robot and the beacon. The sensing
sensitivity is set by expose_time*/

void ReadPD(){
	SensorValue[digital11] = 1; // close the shutter, clear the film, and increment the counter
	SensorValue[digital12] = 1; // initialize counter value to '0'
	SensorValue[digital12] = 0; // allow counter to count
	delay(5); // 5ms wait for things settling down
	SensorValue[digital11] = 0; // open shutter and expose film
	delay(expose_time); // expose time = 3ms to 8ms (can be adjusted)
	PD0 = SensorValue[analog1];
	PD1 = Expose_and_read();
	PD2 = Expose_and_read();
	PD3 = Expose_and_read();
	PD4 = Expose_and_read();
	PD5 = Expose_and_read();
	PD6 = Expose_and_read();
	PD7 = Expose_and_read();
	PD_sum = PD0 + PD1 + PD2 + PD3 + PD4 + PD5 + PD6 + PD7;
}

/*This function compares the magnitude of the variables PD0~PD7 and stores the maximum value
in max_val and the number of the photo diode that has the maximum value in max_no.*/

void Find_max(){
	max_val = PD0; // default = PD0;
	max_no = 0;

	if(PD1 > max_val){
		max_val = PD1;
		max_no = 1;
	}
	if(PD2 > max_val){
		max_val = PD2;
		max_no = 2;
	}
	if(PD3 > max_val){
		max_val = PD3;
		max_no = 3;
	}
	if(PD4 > max_val){
		max_val = PD4;
		max_no = 4;
	}
	if(PD5 > max_val){
		max_val = PD5;
		max_no = 5;
	}
	if(PD6 > max_val){
		max_val = PD6;
		max_no = 6;
	}
	if(PD7 > max_val){
		max_val = PD7;
		max_no = 7;
	}
}

/*
Limits results of move function to max speed	and output to the motors*/
int limit_pwm(int temp){
	int limited = 0;

	if(temp > 127){
		limited = 127;
	} else if (temp < -127){
		limited = -127;
	} else{
		limited = temp;
	}

	return limited;

}

/*Move function helps to check if beacon is found or otherwise it will be search mode	 looking for the beacon.
This function also calculates the speed, steering sensitivity and the heading direction so the robot moves to beacon*/

void Move(){
	int tempSpeed = 0;
	int error = 4 - max_no;//heading direction error , if PD4==max_no, then no error
	int steer = error * steer_sensitivity;//steering effort is proportioinal to heading error
	int speed = forward_speed;//forward speed (normal speed)

	if(PD_sum < ambient_level){ // looking for the beacon if background noise is
		speed = 0;//serach mode=>no forward motion
		steer = -spin_speed;//search mode =>spin
	}
	if(PD_sum > slow_level){//Beacon is near!
		speed = slow_speed;//slow down
	}
	// deleted the stop statement when the beacon is found, because we'll	 use the limit switch to stop the motors	which is more reliable.


	tempSpeed = limit_pwm(steer + speed);
	motor[port1] = tempSpeed; // right, port 1
	tempSpeed = limit_pwm(steer - speed);
	motor[port10] = tempSpeed; // left, port	 10
}

void Press_arm(){
	// Arm down ? press the beacon button
	motor[port2] = arm_down_speed;
	delay(arm_down_time);
	motor[port2] = 0;

	// Brief pause while button is held down
	delay(arm_pause_time);

	// Arm up ? retract to starting position
	motor[port2] = arm_up_speed;
	delay(arm_up_time);
	motor[port2] = 0;
}

/*
The GOBEACON main program essentially sets up all the configuration variables and repeatedly
execute the three routines: Read_PD, find_max, and move.*/
task main(){
	freq = 0; // 0 = 1khz (red) 1 = 10khz (green)
	ambient_level = 200; // used in 'move'
	slow_level = 5000;// used in move
	stop_level = 6000;//used in move
	expose_time = 5; // expose time was changed from 3ms to 5ms (3ms in easyC -> 5ms in RobotC)
	steer_sensitivity = 20;//used in move
	forward_speed = 95;//forward speed , used in move
	slow_speed = 75;//slow speed , used in move
	spin_speed = 70;//spin speed (for searching mode),used in move
	SensorValue[digital10] = freq;// turn to 1KHz(red beacon)
	arm_down_speed    = -127;  // negative = arm moves downward
	arm_up_speed      = 127;   // positive = arm moves upward
	arm_down_time     = 500;  // ms to push arm down
	arm_up_time       = 500;  // ms to raise arm back up
	arm_pause_time    = 200;  // ms to hold at bottom of press

	int state = 1;

	while(SensorValue[limitSwitch] == 0){
		ReadPD();
		Find_max();
		Move();
	}

	motor[port1]  = 0;
	motor[port10] = 0;

	// Phase 2: Repeatedly press the arm down to turn off the beacon.
	// After each press, read the IR sensor to check if the beacon is still on.
	// Stop once the beacon is confirmed off (PD_sum drops below ambient_level).
	delay(300); // short settle before starting arm presses

	ReadPD(); // initial reading to check if beacon is still on
	while(PD_sum >= ambient_level){
		Press_arm();
		delay(300); // wait for beacon state to settle after press
		ReadPD();   // re-read sensor to check if beacon turned off
	}

	// Beacon is off ? ensure arm motor is stopped.
	motor[port2] = 0;

	// Red beacon is off — stop arm motor.
	motor[port2] = 0;

	// ========== Phase 3: Raise arm, switch to green beacon, drive toward it ==========
	// Raise the arm to clear position before moving
	motor[port2] = arm_up_speed;
	delay(arm_up_time);
	motor[port2] = 0;

	// Switch IR sensor to 10kHz (green beacon)
	freq = 1;
	SensorValue[digital10] = freq;
	delay(200); // settle time after frequency switch

	// Drive toward the green beacon until the limit switch is pressed.
	while(SensorValue[limitSwitch] == 0){
		ReadPD();
		Find_max();
		Move();
	}

	// Limit switch triggered — robot has reached the green beacon. Stop drive motors.
	motor[port1]  = 0;
	motor[port10] = 0;

	// ========== Phase 4: Swing arm down forever to capture the green beacon ==========
	motor[port2] = arm_down_speed;

	// ========== Phase 5: Spin to find open exit, then drive backward out ==========
	// Rotate in place until the rear range sensor detects no wall (open exit).
	while(SensorValue[rangeSensor] < no_wall_threshold){
		motor[port1]  =  limit_pwm(scan_spin_speed);   // right forward
		motor[port10] = -limit_pwm(scan_spin_speed);   // left backward -> robot spins
	}

	// Open exit found — drive backward at max speed to leave the arena.
	// Arm stays down to hold the captured green beacon.
	motor[port1]  = -127;  // right motor full reverse
	motor[port10] = -127;  // left motor full reverse




}
