#pragma config(Sensor, in1,    analog1,        sensorAnalog)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  rangeSensor,    sensorSONAR_inch)
#pragma config(Sensor, dgtl10, digital10,      sensorDigitalOut)
#pragma config(Sensor, dgtl11, digital11,      sensorDigitalOut)
#pragma config(Sensor, dgtl12, digital12,      sensorDigitalOut)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           armMotor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Sensor, dgtl5,  frontLeftLimit,  sensorTouch)
 #pragma config(Sensor, dgtl4,  frontRightLimit, sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// robotNoSonar.c  Exit variant that does NOT use the sonar.
// After capturing green, the robot pivots a sharp 90 degrees in place
// then drives straight forward for a fixed duration. Intended for
// setups where the robot's pose after capture makes the opening
// reachable with a single right-angle turn.

// ======================================================
// Mission states
// ======================================================
#define SEARCH_RED      0
#define APPROACH_RED    1
#define PRESS_RED       2
#define VERIFY_RED      3
#define CLEAR_RED       4
#define SEARCH_GREEN    5
#define APPROACH_GREEN  6
#define CAPTURE_GREEN   7
#define TURN_EXIT       8
#define DRIVE_OUT       9
#define DONE            10

// ======================================================
// Beacon frequencies
// ======================================================
#define FREQ_RED    0
#define FREQ_GREEN  1

// ======================================================
// Tunable parameters
// ======================================================

// IR timing (match draft1.c)
int settle_ms      = 5;
int expose_time    = 8;

// Detection thresholds
int red_acquire_sum     = 220;
int red_lost_sum        = 170;
int red_near_sum        = 2400;
int red_close_sum       = 4200;
int red_confirm_sum     = 2800;
int red_off_sum         = 120;

int green_acquire_sum   = 180;
int green_lost_sum      = 150;
int green_near_sum      = 2400;
int green_close_sum     = 4200;
int green_confirm_sum   = 2800;

int cross_margin        = 220;

// Speed schedule
int search_spin_speed   = 50;

int red_fast_speed      = 95;
int red_mid_speed       = 70;
int red_slow_speed      = 42;

int green_fast_speed    = 82;
int green_mid_speed     = 60;
int green_slow_speed    = 36;

// PD heading control  aggressive, no slowdown near beacon
float Kp = 5;
float Kd = 1.2;
int center_deadband = 1;

// Arm  hard swing, long dwell
int arm_down_speed   = -127;
int arm_up_speed     = 127;
int arm_hold_speed   = -30;

int arm_press_time   = 550;
int arm_release_time = 450;
int arm_pause_time   = 200;
int arm_capture_time = 500;

// Motion timing
int post_press_back_ms   = 500;
int clear_turn_ms        = 160;
int seat_nudge_ms        = 70;
int capture_push_ms      = 70;

int exit_turn_speed      = 80;
int exit_drive_speed     = 127;
int exit_turn_90_ms      = 1000;   // ~90 deg pivot at exit_turn_speed
int exit_drive_time_ms   = 4000;  // long enough to clear the opening
int exit_turn_15_ms = 170;
int wall_distance_in = 17;

// ======================================================
// Globals
// ======================================================
int state = SEARCH_RED;

int PD[8];
int PD_sum = 0;
int PD_max = 0;
int PD_max_idx = 0;
int PD_bearing = 0;

int lastSeenSign = 1;
int lostCount = 0;
int lastError = 0;

int no_wall_threshold = 300;




const int W[8] = {-35, -25, -15, -5, 5, 15, 25, 35};

// ======================================================
// Utility
// ======================================================
int clamp127(int x)
{
  if(x > 127) return 127;
  if(x < -127) return -127;
  return x;
}

int iabs(int x)
{
  if(x < 0) return -x;
  return x;
}

int signum(int x)
{
  if(x > 0) return 1;
  if(x < 0) return -1;
  return 0;
}

void setDrive(int leftPwm, int rightPwm)
{
  motor[leftMotor]  = clamp127(leftPwm);
  motor[rightMotor] = clamp127(rightPwm);
}

void stopDrive()
{
  motor[leftMotor]  = 0;
  motor[rightMotor] = 0;
}

void stopAllMotion()
{
  stopDrive();
  motor[armMotor] = 0;
}

// ======================================================
// IRB read
// ======================================================
int exposeAndRead()
{
  // digital11 rising edge closes shutter and advances the PD counter;
  // falling edge opens shutter to begin the next exposure.
  SensorValue[digital11] = 1;
  wait1Msec(settle_ms);
  SensorValue[digital11] = 0;
  wait1Msec(expose_time);
  return SensorValue[analog1];
}

int currentFreq = -1;

void setFreq(int freq)
{
  if(freq == currentFreq) return;
  SensorValue[digital10] = freq;
  wait1Msec(20);
  currentFreq = freq;
}

void readIR8(int freq)
{
  int i;
  long weighted = 0;

  setFreq(freq);

  SensorValue[digital11] = 1;
  SensorValue[digital12] = 1;
  SensorValue[digital12] = 0;
  wait1Msec(settle_ms);
  SensorValue[digital11] = 0;
  wait1Msec(expose_time);
  PD[0] = SensorValue[analog1];

  for(i = 1; i < 8; i++)
  {
    PD[i] = exposeAndRead();
  }

  PD_sum = 0;
  PD_max = PD[0];
  PD_max_idx = 0;

  for(i = 0; i < 8; i++)
  {
    PD_sum += PD[i];
    weighted += (long)PD[i] * (long)W[i];

    if(PD[i] > PD_max)
    {
      PD_max = PD[i];
      PD_max_idx = i;
    }
  }

  if(PD_sum > 0)
    PD_bearing = (int)(weighted / PD_sum);
  else
    PD_bearing = 0;

  if(iabs(PD_bearing) > 2)
  {
    lastSeenSign = signum(PD_bearing);
    if(lastSeenSign == 0) lastSeenSign = 1;
  }
}

int dominantBeacon(int targetFreq, int otherFreq)
{
  int targetSum, otherSum;

  readIR8(targetFreq);
  targetSum = PD_sum;

  readIR8(otherFreq);
  otherSum = PD_sum;

  readIR8(targetFreq);

  if(targetSum > otherSum + cross_margin) return 1;
  return 0;
}

// ======================================================
// Motion controller
// ======================================================
void driveToBeaconPD(int nearSum, int closeSum, int fastSpd, int midSpd, int slowSpd)
{
  int error = PD_bearing;
  int deriv = error - lastError;
  int steer = (int)(Kp * error + Kd * deriv);
  int base  = fastSpd;   // full speed all the way in; limit switch stops us

  lastError = error;

  if(iabs(error) <= center_deadband) steer = 0;

  setDrive(base + steer, base - steer);
}

void searchSpin()
{
  if(lastSeenSign >= 0)
    setDrive(search_spin_speed, -search_spin_speed);
  else
    setDrive(-search_spin_speed, search_spin_speed);
}

// ======================================================
// Arm and contact actions
// ======================================================
void pressRedAction()
{
  stopDrive();

  setDrive(18, 18);
  wait1Msec(seat_nudge_ms);
  stopDrive();

  // Swing the arm down hard, but bail out the moment the beacon
  // goes off so we don't keep pressing past the click and toggle it
  // back on. readIR8 takes ~80 ms, which is our poll interval.
  motor[armMotor] = arm_down_speed;
  clearTimer(T3);
  while(time1[T3] < arm_press_time)
  {
    readIR8(FREQ_RED);
    if(PD_sum < red_off_sum)
    {
      break;
    }
  }
  motor[armMotor] = 0;

  wait1Msec(arm_pause_time);

  motor[armMotor] = arm_up_speed;
  wait1Msec(arm_release_time);
  motor[armMotor] = 0;
}

void clearFromRed()
{
  clearTimer(T1);
  setDrive(-90, -90);
  while(time1[T1] < post_press_back_ms) wait1Msec(5);
  stopDrive();

  setDrive(55, -55);
  wait1Msec(clear_turn_ms);
  stopDrive();
}

void captureGreenAction()
{
  stopDrive();

  motor[armMotor] = arm_down_speed;
  wait1Msec(arm_capture_time);

  motor[armMotor] = arm_hold_speed;

  setDrive(25, 25);
  wait1Msec(capture_push_ms);
  stopDrive();
}

// ======================================================
// Fixed-angle exit (sonar-free)
// ======================================================
void turn90Exit()
{
  stopDrive();
  clearTimer(T2);
  // Spin the opposite direction so the pivot faces the arena opening,
  // not back into the arena.
  setDrive(-exit_turn_speed, exit_turn_speed);
  while(time1[T2] < exit_turn_90_ms)
  {
    wait1Msec(5);
  }
  stopDrive();
}

void driveOutBlind()
{
  clearTimer(T2);
  setDrive(exit_drive_speed, exit_drive_speed);
  while(time1[T2] < exit_drive_time_ms)
  {
    wait1Msec(10);
  }
  stopDrive();
}

// ======================================================
// Main
// ======================================================
task main()
{
  state = SEARCH_RED;
  lostCount = 0;
  lastSeenSign = 1;
  lastError = 0;
  motor[armMotor] = 0;

  // Start spinning immediately so the robot is already turning during
  // the first IR read (setFreq waits 200 ms on first call).
  searchSpin();

  while(true)
  {
    switch(state)
    {
      case SEARCH_RED:
        searchSpin();
        readIR8(FREQ_RED);

        if(PD_sum > red_acquire_sum)
        {
          stopDrive();
          lostCount = 0;
          lastError = 0;
          state = APPROACH_RED;
        }
        break;

      case APPROACH_RED:
        readIR8(FREQ_RED);

        if(PD_sum < red_lost_sum)
        {
          lostCount++;
          if(lostCount > 4)
          {
            state = SEARCH_RED;
            stopDrive();
            break;
          }
          searchSpin();
          break;
        }
        lostCount = 0;

        if(PD_sum > red_confirm_sum && iabs(PD_bearing) < 10)
        {
          if(!dominantBeacon(FREQ_RED, FREQ_GREEN))
          {
            state = SEARCH_RED;
            stopDrive();
            break;
          }
        }

        if(SensorValue[limitSwitch] == 1)
        {
          stopDrive();
          state = PRESS_RED;
          break;
        }

        driveToBeaconPD(red_near_sum, red_close_sum,
                        red_fast_speed, red_mid_speed, red_slow_speed);
        break;

      case PRESS_RED:
        pressRedAction();
        state = VERIFY_RED;
        break;

      case VERIFY_RED:
        readIR8(FREQ_RED);

        if(PD_sum < red_off_sum)
        {
          state = CLEAR_RED;
        }
        else
        {
          state = PRESS_RED;
        }
        break;

      case CLEAR_RED:
        clearFromRed();
        state = SEARCH_GREEN;
        break;

      case SEARCH_GREEN:
        readIR8(FREQ_GREEN);

        if(PD_sum > green_acquire_sum)
        {
          lostCount = 0;
          lastError = 0;
          state = APPROACH_GREEN;
        }
        else
        {
          searchSpin();
        }
        break;

      case APPROACH_GREEN:
        readIR8(FREQ_GREEN);

        if(PD_sum < green_lost_sum)
        {
          lostCount++;
          if(lostCount > 4)
          {
            state = SEARCH_GREEN;
            stopDrive();
            break;
          }
          searchSpin();
          break;
        }
        lostCount = 0;

        if(PD_sum > green_confirm_sum && iabs(PD_bearing) < 10)
        {
          if(!dominantBeacon(FREQ_GREEN, FREQ_RED))
          {
            state = SEARCH_GREEN;
            stopDrive();
            break;
          }
        }

        if(SensorValue[limitSwitch] == 1)
        {
          stopDrive();
          state = CAPTURE_GREEN;
          break;
        }

        driveToBeaconPD(green_near_sum, green_close_sum,
                        green_fast_speed, green_mid_speed, green_slow_speed);
        break;

      case CAPTURE_GREEN:
        captureGreenAction();
        state = TURN_EXIT;
        break;

      case TURN_EXIT:
        // Sharp right-angle pivot toward the opening. No scan, no sonar.
        turn90Exit();
        state = DRIVE_OUT;
        break;

      case DRIVE_OUT:
    int r;                                                                                                                     
    int count = 0; 
    while(true)
    {
      // ---- Wall ahead: sonar < 15 in -> pivot right 90 deg ----
      r = SensorValue[rangeSensor];                                                                                            
      if(r > 0 && r < wall_distance_in)                                                                                        
      {                                                                                                                        
        motor[leftMotor]  = 0;                                                                                                 
        motor[rightMotor] = 0;
        clearTimer(T2);                                                                                                        
        motor[leftMotor]  =  exit_turn_speed;   // left fwd
        motor[rightMotor] = -exit_turn_speed;   // right rev -> pivot right                                                    
        while(time1[T2] < exit_turn_90_ms) wait1Msec(5);
        motor[leftMotor]  = 0;                                                                                                 
        motor[rightMotor] = 0;
        continue;                                                                                                              
      }           

      // ---- Front-LEFT edge hit: robot angled into wall on the left ----                                                     
      // -> nudge 15 deg RIGHT to re-square.
      if(SensorValue[frontLeftLimit] == 1)                                                                                     
      {                                                                                                                        
        motor[leftMotor]  = 0;
        motor[rightMotor] = 0;                                                                                                 
        clearTimer(T2);
        motor[leftMotor]  =  exit_turn_speed;
        motor[rightMotor] = -exit_turn_speed;                                                                                  
        while(time1[T2] < exit_turn_15_ms) wait1Msec(5);
        motor[leftMotor]  = 0;                                                                                                 
        motor[rightMotor] = 0;
        continue;                                                                                                              
      }           

      // ---- Front-RIGHT edge hit: robot angled into wall on the right ----                                                   
      // -> nudge 15 deg LEFT to re-square.
      if(SensorValue[frontRightLimit] == 1)                                                                                    
      {           
        motor[leftMotor]  = 0;
        motor[rightMotor] = 0;                                                                                                 
        clearTimer(T2);
        motor[leftMotor]  = -exit_turn_speed;                                                                                  
        motor[rightMotor] =  exit_turn_speed;
        while(time1[T2] < exit_turn_15_ms) wait1Msec(5);                                                                       
        motor[leftMotor]  = 0;
        motor[rightMotor] = 0;                                                                                                 
        continue;                                                                                                              
      }
                                                                                                                               
      // ---- Default: drive forward ----
      motor[leftMotor]  = exit_drive_speed;
      motor[rightMotor] = exit_drive_speed;
      wait1Msec(10);                                                                                                           
    }
        state = DONE;
        break;

      case DONE:
        stopDrive();
        motor[armMotor] = arm_hold_speed;
        while(true)
        {
          wait1Msec(1000);
        }
        break;
    }
  }
}
