#pragma config(Sensor, in1,    analog1,     sensorAnalog)
#pragma config(Sensor, dgtl1,  limitSwitch, sensorTouch)
#pragma config(Sensor, dgtl2,  rangeSensorOut, sensorDigitalOut)
#pragma config(Sensor, dgtl3,  rangeSensorIn,  sensorDigitalIn)
#pragma config(Sensor, dgtl10, digital10,   sensorDigitalOut)
#pragma config(Sensor, dgtl11, digital11,   sensorDigitalOut)
#pragma config(Sensor, dgtl12, digital12,   sensorDigitalOut)
#pragma config(Motor,  port1,  rightMotor,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10, leftMotor,   tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,  armMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard             !!*//

// Global Variables
int freq, ambient_level, slow_level, expose_time, steer_sensitivity, forward_speed, slow_speed, spin_speed;

// Arm parameters
int arm_down_speed, arm_up_speed, arm_down_time, arm_up_time, arm_pause_time;

// Range sensor and exit parameters
int no_wall_threshold, scan_spin_speed;

// PD values for all 8 photodiodes and their sum
int PD0, PD1, PD2, PD3, PD4, PD5, PD6, PD7, PD_sum;
// Max signal value and the photodiode index that holds it
int max_val, max_no = 0;

/*The accumulator accumulates the rectified signal over a period of time set by expose_time.
The accumulated voltage is read via analog1. Longer expose_time = more sensitivity.*/
int Expose_and_read(){
	SensorValue[digital11] = 1; // close shutter, clear accumulator, advance counter
	delay(5);                   // 5ms settle time
	SensorValue[digital11] = 0; // open shutter for exposure
	delay(expose_time);         // expose_time = 5ms (adjustable 3-8ms)
	int intensity = SensorValue[analog1];
	return intensity;
}

/*Read_PD sequences through all 8 photodiodes using the Johnson counter (digital12)
and shutter (digital11). PD_sum is the total IR intensity — a measure of distance
to the beacon. Higher PD_sum = closer beacon.*/
void ReadPD(){
	SensorValue[digital11] = 1; // close shutter
	SensorValue[digital12] = 1; // reset counter to 0
	SensorValue[digital12] = 0; // allow counter to count
	delay(5);                   // 5ms settle time
	SensorValue[digital11] = 0; // open shutter, expose PD0
	delay(expose_time);
	PD0 = SensorValue[analog1];
	PD1 = Expose_and_read();    // counter auto-advances each call
	PD2 = Expose_and_read();
	PD3 = Expose_and_read();
	PD4 = Expose_and_read();
	PD5 = Expose_and_read();
	PD6 = Expose_and_read();
	PD7 = Expose_and_read();
	PD_sum = PD0 + PD1 + PD2 + PD3 + PD4 + PD5 + PD6 + PD7;
}

/*Find_max scans PD0-PD7 and stores the brightest photodiode index in max_no.
max_no is the heading reference used by Move() to steer toward the beacon.*/
void Find_max(){
	max_val = PD0;
	max_no  = 0;

	if(PD1 > max_val){ max_val = PD1; max_no = 1; }
	if(PD2 > max_val){ max_val = PD2; max_no = 2; }
	if(PD3 > max_val){ max_val = PD3; max_no = 3; }
	if(PD4 > max_val){ max_val = PD4; max_no = 4; }
	if(PD5 > max_val){ max_val = PD5; max_no = 5; }
	if(PD6 > max_val){ max_val = PD6; max_no = 6; }
	if(PD7 > max_val){ max_val = PD7; max_no = 7; }
}

/*Clamps motor commands to the valid VEX PWM range of -127 to +127.*/
int limit_pwm(int temp){
	if(temp >  127) return  127;
	if(temp < -127) return -127;
	return temp;
}

/*Move calculates motor outputs based on beacon direction and distance.
Three states:
  1. Beacon not detected (PD_sum < ambient_level): spin in place to search.
  2. Beacon detected, far (ambient_level <= PD_sum <= slow_level): drive at full speed,
     steering proportional to heading error.
  3. Beacon detected, near (PD_sum > slow_level): slow down and continue steering.
The limit switch is the final stop — handled in main().*/
void Move(){
	int error = 4 - max_no;          // PD4 is center-forward; error = 0 means aim is straight
	int steer = error * steer_sensitivity; // proportional steering effort
	int speed = forward_speed;

	if(PD_sum < ambient_level){
		// Beacon not found — spin in place to scan for it.
		motor[port1]  =  limit_pwm(spin_speed);  // right forward
		motor[port10] = -limit_pwm(spin_speed);  // left backward -> robot spins
		return;
	}

	if(PD_sum > slow_level){
		speed = slow_speed; // beacon is close, reduce speed
	}

	// Differential drive: right = steer + speed, left = steer - speed.
	motor[port1]  = limit_pwm(steer + speed); // right motor
	motor[port10] = limit_pwm(steer - speed); // left motor
}

/*Press_arm pushes the arm downward, pauses, then raises it back up.
One full press cycle to hit the beacon button.*/
void Press_arm(){
	// Arm down — press the beacon button
	motor[port2] = arm_down_speed;
	delay(arm_down_time);
	motor[port2] = 0;

	// Brief pause while button is held down
	delay(arm_pause_time);

	// Arm up — retract to starting position
	motor[port2] = arm_up_speed;
	delay(arm_up_time);
	motor[port2] = 0;
}

/*Main initializes all parameters, then executes five phases:
  Phase 1: Drive toward red beacon (1kHz) until limit switch triggers.
  Phase 2: Press arm to turn off red beacon until IR confirms it is off.
  Phase 3: Raise arm, switch to green beacon (10kHz), drive toward it.
  Phase 4: At green beacon, swing arm down to capture it.
  Phase 5: Spin to scan with range sensor, find open exit, drive backward out.*/
task main(){
	freq              = 0;    // 0 = 1kHz red beacon, 1 = 10kHz green beacon
	ambient_level     = 200;  // minimum PD_sum to consider beacon detected
	slow_level        = 5000; // PD_sum threshold to switch to slow approach speed
	expose_time       = 5;    // IR accumulator exposure time in ms (3-8ms range)
	steer_sensitivity = 20;   // proportional steering gain
	forward_speed     = 35;   // normal drive speed
	slow_speed        = 25;   // reduced speed when beacon is near
	spin_speed        = 50;   // search spin speed

	// Arm tuning parameters
	arm_down_speed    = -80;  // negative = arm moves downward
	arm_up_speed      = 80;   // positive = arm moves upward
	arm_down_time     = 500;  // ms to push arm down
	arm_up_time       = 500;  // ms to raise arm back up
	arm_pause_time    = 200;  // ms to hold at bottom of press

	// Range sensor and exit parameters
	no_wall_threshold = 888;  // range reading above this = no wall (open exit)
	scan_spin_speed   = 65;   // spin speed when scanning for exit (faster than search)

	SensorValue[digital10] = freq; // set IR sensor to 1kHz (red beacon)

	// ========== Phase 1: Drive toward the red beacon ==========
	while(SensorValue[limitSwitch] == 0){
		ReadPD();
		Find_max();
		Move();
	}

	// Limit switch triggered — robot has reached the red beacon. Stop drive motors.
	motor[port1]  = 0;
	motor[port10] = 0;

	// ========== Phase 2: Press arm to turn off the red beacon ==========
	delay(300); // short settle before starting arm presses

	ReadPD(); // initial reading to check if beacon is still on
	while(PD_sum >= ambient_level){
		Press_arm();
		delay(300); // wait for beacon state to settle after press
		ReadPD();   // re-read sensor to check if beacon turned off
	}

	// Red beacon is off — stop arm motor.
	motor[port2] = 0;

	// ========== Phase 3: Raise arm, switch to green beacon, drive toward it ==========
	// Raise the arm to clear position before moving
	motor[port2] = arm_up_speed;
	delay(arm_up_time);
	motor[port2] = 0;

	// Switch IR sensor to 10kHz (green beacon)
	freq = 1;
	SensorValue[digital10] = freq;
	delay(200); // settle time after frequency switch

	// Drive toward the green beacon until the limit switch is pressed.
	while(SensorValue[limitSwitch] == 0){
		ReadPD();
		Find_max();
		Move();
	}

	// Limit switch triggered — robot has reached the green beacon. Stop drive motors.
	motor[port1]  = 0;
	motor[port10] = 0;

	// ========== Phase 4: Swing arm down forever to capture the green beacon ==========
	motor[port2] = arm_down_speed;

	// ========== Phase 5: Spin to find open exit, then drive backward out ==========
	// Rotate in place until the rear range sensor detects no wall (open exit).
	while(SensorValue[rangeSensor] < no_wall_threshold){
		motor[port1]  =  limit_pwm(scan_spin_speed);   // right forward
		motor[port10] = -limit_pwm(scan_spin_speed);   // left backward -> robot spins
	}

	// Open exit found — drive backward at max speed to leave the arena.
	// Arm stays down to hold the captured green beacon.
	motor[port1]  = -127;  // right motor full reverse
	motor[port10] = -127;  // left motor full reverse
}
